[build]
	command = "pnpm run build"
	publish = "build"

[dev]
  command = "pnpm run dev"
  targetPort = 5173
  framework = "#custom"
  autoLaunch = false
 
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
